config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', to: "users#admin", as: 'rails_admin'

  devise_for :users
  resources :users, only: [:show]
  resources :notes
  resources :orders
  resources :carts
  get '/add_cart/:id', to: 'carts#create', as: 'add_cart'
  get '/checkout', to: 'checkouts#checkout', as: 'checkout'
  get '/add_favory/:id', to: 'favories#create', as: 'add_favory'
  get '/delete_cart/:id', to: 'carts#destroy', as: 'delete_cart'
  get '/delete_favory/:id', to: 'favories#destroy', as: 'delete_favory'
  get '/delete_order/:id', to: 'orders#destroy', as: 'delete_order'
  get '/add_order/:indice', to: 'orders#create', as: 'add_order'
  # get '/profil/:id', to: 'users#show', as: 'profil'
  resources :favories
  resources :products
  resources :categories
  root to: "pages#home"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products, dependent: :destroy
end

app/models/favory.rb
class Favory < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user, optional: true

  validates :user_id, uniqueness: {scope: :product_id} 
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  validates :total_price, :qt_product, presence: true

  has_and_belongs_to_many :products, optional: true

  belongs_to :user, optional: false

  has_one :note

  enum status: {
        progress: 0,
        complete: 1
  }

end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category, optional: true

  has_many :favories, dependent: :destroy

  has_many :carts, dependent: :destroy

  # has_many :cart_users, through: :carts, source: :user

  has_and_belongs_to_many :orders, dependent: :destroy

  validates :name, :description, :price, :image, presence: true

  validates :name,  uniqueness: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :address, :email, :encrypted_password, :telephone, presence: true

  has_many :carts, dependent: :destroy
  # has_many :cart_products, through: :carts, source: :product
  has_many :orders, dependent: :destroy

  has_many :favories, dependent: :destroy

  # has_many :favorite_users, through: :favorites, source: :user

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @carts = current_user.carts.all
    @tax = 20

    @subtotal = 0

    @carts.each do |c|
      @subtotal = @subtotal + c.total_price
    end

    @total = @subtotal + @tax
  end

  def create
    cart = current_user.carts.create(product_id: params[:id], user_id: current_user.id)
    redirect_to carts_path()
  end

  def destroy
    cart = current_user.carts.find_by(user_id: current_user.id, product_id: params[:id]).destroy
    redirect_to carts_path()
  end

  def update
    @cart = current_user.carts.find(params[:id])
    @cart.update(cart_params)
    @cart.total_price = @cart.quantity * @cart.product.price
    redirect_to carts_path
    @cart.save
  end

  private

    def cart_params
      params.require(:cart).permit(:quantity)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:order_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = current_user.orders.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    commands = current_user.carts.all
    @order = Order.new()
    @total = 20
    @qtproduct = 0
    commands.each do |c|
      @total = @total + c.total_price
      @qtproduct = @qtproduct + c.quantity
    end
    @order.total_price = @total
    @order.qt_product = @qtproduct
    @order.user_id = current_user.id
    @order.save

    commands.each do |c|
      @cmde = OrdersProduct.new()
      @cmde.order_id = @order.id
      @cmde.product_id = c.product.id
      @cmde.save
    end

    if @order.total_price > 20
      redirect_to "/checkout"

    else
      redirect_to carts_path
    end

    d = commands.delete_all
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    order = current_user.orders.find_by(user_id: current_user.id, id: params[:id]).destroy
    redirect_to orders_path()
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:total_price, :qt_product, :product_id, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
    @products = Product.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favories_helper.rb
module FavoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/index.html.erb
<!------Carts page-------->
<div class="small-container cart-page">
    <h2 class="title">Cart</h2>
   <table>
     <tr>
       <th>Product</th>
       <th>Quantity</th>
       <th>Subtotal</th>
     </tr>
     <% @carts.each do |c| %>
       <tr>
         <td>
           <div class="cart-info">
             <img src="<%= c.product.image.url %>" alt="">
             <div>
               <p><%= c.product.name %></p>
               <small>Price: <%= c.product.price %></small>
               <br>
               <%= link_to "Remove", delete_cart_path(id: c.product.id), method: :delete%>
             </div>
           </div>
         </td>
         <td>
          <%= form_for(c) do |f| %>
            <div class="field">
              <%= f.number_field :quantity, class:"quantity", in: 1..20, step: 1%>
            </div>

            <div class="field">
              <%= hidden_field_tag "id", c.product.id  %>
            </div>

            <div class="actions">
              <%= f.submit "Update", class:"btn-update" %>
            </div>
          <% end %>
         </td>
         <td>
           <%= c.total_price %>
         </td>
       </tr>
     <% end %>
   </table>

   <div class="total-price">
     <table>
       <tr>
         <td>Subtotal</td>
         <td><%= @subtotal %>$</td>
       </tr>
       <tr>
         <td>Tax</td>
         <td><%= @tax %>$</td>
       </tr>
       <tr>
         <td>Total</td>
         <td><%= @total %>$</td>
       </tr>
     </table>
   </div>

   <% if @total > 20 %>
     <a href="<%= add_order_path(indice: @total) %>", class="btn-update valid">Validate</a>
   <% else %>
     <p style="color:red;">Clique to update</p>
   <% end %>

</div>

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.order %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @note.order %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/orders/index.html.erb
<div class="small-container cart-page">
    <h2 class="title">Ckeckout / Orders</h2>

    <table>
      <tr>
        <th>id</th>
        <th>Username</th>
        <th>Telephone</th>
        <th>Address</th>
        <th>Quantity of products</th>
        <th>Total price</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
      <% @orders.each do |o| %>
        <tr>
          <td>
            <%= o.id %>
          </td>
          <td>
            <%= o.user.username %>
          </td>
          <td>
            <%= o.user.telephone %>
          </td>
          <td>
            <%= o.user.address %>
          </td>
          <td>
            <%= o.qt_product %>
          </td>
          <td>
            <%= o.total_price %>
          </td>
          <td>
            <% if o.status == "progress" %>
              <p style="color:#FAC800"><%= o.status %></p>
            <%else%>
              <p style="color:#00FA00"><%= o.status %></p>
            <%end%>
          </td>
          <td>
            <%= link_to "Delete", delete_order_path(id: o.id), method: :delete%>
          </td>
        </tr>
      <% end %>
    </table>
</div>

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>

app/views/users/show.html.erb
<div class="small-container" style="margin-top:30px;">
  <h2 class="title" id="">Personnal Informations</h2>
  <div class="row" style="display:inline-block;">
    <p>
      <strong style="color:purple;">Username: </strong> <%= @user.username %>
    </p><br>
    <p>
      <strong style="color:purple;">Email: </strong> <%= @user.email %>
    </p><br>
    <p>
      <strong style="color:purple;">Telephone: </strong> <%= @user.telephone %>
    </p><br>
    <p>
      <strong style="color:purple;">Address: </strong> <%= @user.address %>
    </p>
  </div>
  <div class="">
    <a href="<%= edit_user_registration_path %>" class="profil-edit">Edit profil</a>
  </div>
</div>

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>