config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', to: "users#admin", as: 'rails_admin'

  devise_for :users
  resources :users, only: [:show]
  resources :notes
  resources :orders
  resources :carts
  get '/add_cart/:id', to: 'carts#create', as: 'add_cart'
  get '/checkout', to: 'checkouts#checkout', as: 'checkout'
  get '/add_favory/:id', to: 'favories#create', as: 'add_favory'
  get '/delete_cart/:id', to: 'carts#destroy', as: 'delete_cart'
  get '/delete_favory/:id', to: 'favories#destroy', as: 'delete_favory'
  get '/delete_order/:id', to: 'orders#destroy', as: 'delete_order'
  get '/add_order/:indice', to: 'orders#create', as: 'add_order'
  # get '/profil/:id', to: 'users#show', as: 'profil'
  resources :favories
  resources :products
  resources :categories
  root to: "pages#home"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products, dependent: :destroy
end

app/models/favory.rb
class Favory < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user, optional: true

  validates :user_id, uniqueness: {scope: :product_id} 
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  validates :total_price, :qt_product, presence: true

  has_and_belongs_to_many :products, optional: true

  belongs_to :user, optional: false

  has_one :note

  enum status: {
        progress: 0,
        complete: 1
  }

end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category, optional: true

  has_many :favories, dependent: :destroy

  has_many :carts, dependent: :destroy

  # has_many :cart_users, through: :carts, source: :user

  has_and_belongs_to_many :orders, dependent: :destroy

  validates :name, :description, :price, :image, presence: true

  validates :name,  uniqueness: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :address, :email, :encrypted_password, :telephone, presence: true

  has_many :carts, dependent: :destroy
  # has_many :cart_products, through: :carts, source: :product
  has_many :orders, dependent: :destroy

  has_many :favories, dependent: :destroy

  # has_many :favorite_users, through: :favorites, source: :user

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @carts = current_user.carts.all
    @tax = 20

    @subtotal = 0

    @carts.each do |c|
      @subtotal = @subtotal + c.total_price
    end

    @total = @subtotal + @tax
  end

  def create
    cart = current_user.carts.create(product_id: params[:id], user_id: current_user.id)
    redirect_to carts_path()
  end

  def destroy
    cart = current_user.carts.find_by(user_id: current_user.id, product_id: params[:id]).destroy
    redirect_to carts_path()
  end

  def update
    @cart = current_user.carts.find(params[:id])
    @cart.update(cart_params)
    @cart.total_price = @cart.quantity * @cart.product.price
    redirect_to carts_path
    @cart.save
  end

  private

    def cart_params
      params.require(:cart).permit(:quantity)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:order_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
    @products = Product.all
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, only: [:index, :new, :create]

  # GET /products or /products.json
  def index
    @favories = current_user.favories.all
    @products = Product.all.order(id: :asc)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :image_cache, :price, :references)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favories_helper.rb
module FavoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/products/index.html.erb
<section id="banner-shop">
   <div class="banner-text">
     <h1>It's Shopping Time</h1>
     <p>Let's go !</p>
     <div class="banner-btn">
       <a href="#products"><span></span>Explore</a>
     </div>
   </div>
</section>

<!-- my favories products -->

<div class="small-container">
  <h2 class="title" id="">Favorites Products</h2>
  <div class="row">
    <% @favories.each do |f| %>
      <div class="col-4">
        <a href="<%= product_path(f.product.id) %>">
          <img src="<%= f.product.image.url %>" alt="">
        </a>
        <h4><%= f.product.name %></h4>
        <div class="rating">
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bx-star' ></i>
        </div>
        <p><%= f.product.price %> $</p>
        <a href="<%= delete_favory_path(id: f.id) %>" class="favory-add" style="background:red;">Delete</a>
      </div>
    <% end %>
  </div>
</div>

<!-- all products -->

<div class="small-container">
  <h2 class="title" id="products">All products</h2>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-4">
        <a href="<%= product_path(p) %>">
          <img src="<%= p.image.url %>" alt="">
        </a>
        <h4><%= p.name %></h4>
        <p style="color:red;"><%= p.price %> $</p>
        <a href="<%= add_favory_path(id: p.id) %>" class="favory-add">Favory</a>
      </div>
    <% end %>
  </div>
  <h2 class="title">Latest products</h2>
</div>

<!-- new offer -->
<div class="small-container new-offer">
  <div class="row">
    <div class="col-2">
      <%= image_tag("exclusive.png", :alt => "image", class:"offer-img") %>
      <!-- <img src="/assets/exclusive.png" alt="" class="offer-img"> -->
    </div>
    <div class="col-2 offer-banner-text">
      <h1>Exclusive Available on Redstore</h1>
      <p>Smart Brand 4</p>
      <!-- <a href="#" class="buy">Buy Now</a> -->
    </div>
  </div>
</div>
<!-- testimonial -->

<div class="testimonial">
  <div class="small-container">
    <div class="row">
      <div class="col-3 cart">
        <i class='bx bxs-quote-right'></i>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="rating">
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bx-star' ></i>
        </div>
        <%= image_tag("user-1.png", :alt => "image") %>
        <h3>Marina Grants</h3>
      </div>
      <div class="col-3 cart">
        <i class='bx bxs-quote-right'></i>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="rating">
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bx-star' ></i>
        </div>
        <%= image_tag("user-2.png", :alt => "image") %>
        <h3>Victoria Serb </h3>
      </div>
      <div class="col-3 cart">
        <i class='bx bxs-quote-right'></i>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <div class="rating">
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bx-star' ></i>
        </div>
        <%= image_tag("user-3.png", :alt => "image") %>
        <h3>Paul Peter </h3>
      </div>
    </div>
  </div>
</div>

<!-- footer -->

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>

app/views/products/show.html.erb
<div class="small-container" style="margin-top:20px;">
  <h2 class="title">Details product</h2>
</div>
<section class="product-details">
  <div class="image-details">
    <img src="<%= @product.image.url %>" alt="" width="100%">
  </div>

  <div class="text-details">
    <h1 class="product-title"> <%= @product.name %> </h1>
    <h4>Details products</h4>
    <p class="product-description"> <%= @product.description %> </p>
    <span class="product-price">Price: <%= @product.price %></span>

    <div class="btn-cart">
      <%= link_to "Add to Cart", add_cart_path(id: @product.id), class:"button", style:"background-color: #3296C8;" %>
    	<a href="<%= products_path %>" class="button" style="background-color: #C7325A;">Go to Shop</a>
    </div>
  </div>
</section>

<div class="small-container others">
  <h2 class="title" id="products">Others products</h2>
  <div class="row">
    <% Product.limit(4).each do |p| %>
      <div class="col-4">
        <a href="<%= product_path(p) %>">
          <img src="<%= p.image.url %>" alt="">
        </a>
        <h4><%= p.name %></h4>
        <div class="rating">
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bxs-star'></i>
          <i class='bx bx-star' ></i>
        </div>
        <p><%= p.price %> $</p>
      </div>
    <% end %>
  </div>
</div>

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>