config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', to: "users#admin", as: 'rails_admin'

  devise_for :users
  resources :users, only: [:show]
  resources :notes
  resources :orders
  resources :carts
  get '/add_cart/:id', to: 'carts#create', as: 'add_cart'
  get '/checkout', to: 'checkouts#checkout', as: 'checkout'
  get '/add_favory/:id', to: 'favories#create', as: 'add_favory'
  get '/delete_cart/:id', to: 'carts#destroy', as: 'delete_cart'
  get '/delete_favory/:id', to: 'favories#destroy', as: 'delete_favory'
  get '/delete_order/:id', to: 'orders#destroy', as: 'delete_order'
  get '/add_order/:indice', to: 'orders#create', as: 'add_order'
  # get '/profil/:id', to: 'users#show', as: 'profil'
  resources :favories
  resources :products
  resources :categories
  root to: "pages#home"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products, dependent: :destroy
end

app/models/favory.rb
class Favory < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user, optional: true

  validates :user_id, uniqueness: {scope: :product_id} 
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  validates :total_price, :qt_product, presence: true

  has_and_belongs_to_many :products, optional: true

  belongs_to :user, optional: false

  has_one :note

  enum status: {
        progress: 0,
        complete: 1
  }

end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category, optional: true

  has_many :favories, dependent: :destroy

  has_many :carts, dependent: :destroy

  # has_many :cart_users, through: :carts, source: :user

  has_and_belongs_to_many :orders, dependent: :destroy

  validates :name, :description, :price, :image, presence: true

  validates :name,  uniqueness: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :address, :email, :encrypted_password, :telephone, presence: true

  has_many :carts, dependent: :destroy
  # has_many :cart_products, through: :carts, source: :product
  has_many :orders, dependent: :destroy

  has_many :favories, dependent: :destroy

  # has_many :favorite_users, through: :favorites, source: :user

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @carts = current_user.carts.all
    @tax = 20

    @subtotal = 0

    @carts.each do |c|
      @subtotal = @subtotal + c.total_price
    end

    @total = @subtotal + @tax
  end

  def create
    cart = current_user.carts.create(product_id: params[:id], user_id: current_user.id)
    redirect_to carts_path()
  end

  def destroy
    cart = current_user.carts.find_by(user_id: current_user.id, product_id: params[:id]).destroy
    redirect_to carts_path()
  end

  def update
    @cart = current_user.carts.find(params[:id])
    @cart.update(cart_params)
    @cart.total_price = @cart.quantity * @cart.product.price
    redirect_to carts_path
    @cart.save
  end

  private

    def cart_params
      params.require(:cart).permit(:quantity)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:order_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favories_helper.rb
module FavoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AfrikShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width = device-width, initial-scale=1">

    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script|Tangerine|Cookie|Material+Icons">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

    <div id="sideNav">
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="<%= products_path %>">Go to shop</a></li>
          <li><a href="#footer">Contact</a></li>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><a href="/admin">Dashbord Admin</a></li>
            <% end %>
            <% if current_user.carts.count != 0 %>
              <li><a href="<%= carts_path %>">Cart [<%= current_user.carts.count %>] </a></li>
            <%end%>
            <li><a href="<%= orders_path %>">Orders</a></li>
            <li><a href="<%= user_path(current_user.id) %>">Profil</a></li>
            <li><%= button_to "logout", destroy_user_session_path, method: :delete, class:"btn-logout"%></li
          <% else %>
            <li><a href="#service">Our products</a></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>

    <button type="button" id="menuBtn" name="menu">
      <i class='bx bx-menu bx-md'></i>
    </button>

    <div id="google_translate_element"></div>

    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit">
    </script>

    <script type="text/javascript">
      function googleTranslateElementInit(){
        new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'en,es,fr,ar,de,el,iw,ja', autodisplay:false}, "google_translate_element");
      }
    </script>

    <script type="text/javascript">
      var sideNav = document.getElementById('sideNav');

      // sideNav.style.right = "0px"; //Pour les tests de deconnection décochez la ligne courante et commentez toute celles du dessous

      $("#menuBtn").click(function(){
        if(sideNav.style.right == "-250px"){
          sideNav.style.right = "0";
        }
        else{
          sideNav.style.right = "-250px";
        }
      });
    </script>



  </body>
</html>

app/views/pages/home.html.erb
<section id="banner">
  <div class="banner-text">
    <h1>Welcome to AfrikShop</h1>
    <p>The best of Africa in one store</p>
    <div class="banner-btn">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <a href="/admin"><span></span>Admin</a>
        <% end %>
        <a href="<%= products_path %>"><span></span>Go to Shop</a>
      <% else %>
          <a href="<%= new_user_registration_path %>"><span></span>Sign up</a>
          <a href="<%= new_user_session_path %>"><span></span>Sign in</a>
      <% end %>
    </div>
  </div>
</section>

<section id="feature">
  <div class="title-text">
    <p>Features</p>
    <h1>Why Choose Us</h1>
  </div>
  <div class="feature-box">
    <div class="features">
      <h1>Experienced Staff</h1>
      <div class="feature-desc">
        <div class="feature-icon">
          <i class='bx bx-shield bx-lg'></i>
        </div>
        <div class="feature-text">
          <p>Our agents are always online and ready to answer your questions and above all to validate your orders and authorize deliveries as soon as possible.</p>
        </div>
      </div>
      <h1>Booking Online</h1>
      <div class="feature-desc">
        <div class="feature-icon">
          <i class='bx bx-check-square bx-lg'></i>
        </div>
        <div class="feature-text">
          <p>You can contact us to easily reserve products when our stocks are limited</p>
        </div>
      </div>
      <h1>Affordable Cost</h1>
      <div class="feature-desc">
        <div class="feature-icon">
          <i class='bx bx-rupee bx-lg'></i>
        </div>
        <div class="feature-text">
          <p>Our products come for the most part from the African market, are of quality and at a lower cost.</p>
        </div>
      </div>
    </div>
    <div class="features-img">
      <%= image_tag("market.jpg", :alt => "logo") %>
      <!-- <img src="/assets/market.jpg" alt=""> -->
    </div>
  </div>
</section>

<section id="service">
  <div class="title-text">
    <p>Our Products</p>
    <h1>We Provide the Better</h1>
  </div>

  <div class="service-box">
    <div class="single-service">
      <%= image_tag("2.jpg", :alt => "img") %>
      <!-- <img src="/assets/2.jpg" alt=""> -->
      <div class="overlay"></div>
      <div class="service-desc">
        <h3>Honey</h3>
        <hr>
        <p>Honey is a sweet substance made by bees from the nectar of flowers. Composed of more than 80% carbohydrates, it is a food rich in energy and relatively pure</p>
      </div>
    </div>

    <div class="single-service">
      <%= image_tag("6.jpg", :alt => "img") %>
      <!-- <img src="/assets/6.jpg" alt=""> -->
      <div class="overlay"></div>
      <div class="service-desc">
        <h3>Coconut oil</h3>
        <hr>
        <p>Moisturizing, soothing, antioxidant ... coconut oil is full of benefits. It can be used without moderation on the skin, on the hair, and can replace many beauty products.</p>
      </div>
    </div>

    <div class="single-service">
      <%= image_tag("3.jpg", :alt => "img") %>
      <!-- <img src="/assets/3.jpg" alt=""> -->
      <div class="overlay"></div>
      <div class="service-desc">
        <h3>Palm oil</h3>
        <hr>
        <p>Emollient, nourishing and protective, palm oil is particularly moisturizing, and it is for this reason that it is widely used in soap.</p>
      </div>
    </div>

    <div class="single-service">
      <%= image_tag("5.jpg", :alt => "img") %>
      <!-- <img src="/assets/5.jpg" alt=""> -->
      <div class="overlay"></div>
      <div class="service-desc">
        <h3>Sodabi liquor</h3>
        <hr>
        <p>Sodabi is a type of liquor made from distilled palm wine. Sodabi is more popular in the southern part of the country but can be found in northern markets as well.</p>
      </div>
    </div>
  </div>
</section>

<section id="footer">
  <%= image_tag("benin.jpg", :alt => "img", class:"footer-img") %>
  <!-- <img src="/assets/benin.jpg" alt="" class="footer-img"> -->
  <div class="title-text">
    <p>Contact</p>
    <h1>Visit Shop Today</h1>
  </div>
  <div class="footer-row">
    <div class="footer-left">
      <h2>Opening Hours</h2>
      <p><i class='bx bx-time-five'></i>Monday to Friday - 24H/24H</p>
      <p><i class='bx bx-time-five'></i>Saturday and Sunday - 7am to 3pm</p>
    </div>
    <div class="footer-right">
      <h1>Get In Touch</h1>
      <p>Benin, Cotonou / Abomey-Calavi<i class='bx bx-map-pin'></i></p>
      <p>afrikshop@website.com <i class='bx bxl-google-plus'></i></p>
      <p>+229 00272552 <i class='bx bx-phone'></i></p>
    </div>
  </div>

  <div class="social-links">
    <i class='bx bxl-facebook'></i>
    <i class='bx bxl-instagram'></i>
    <i class='bx bxl-twitter'></i>
    <i class='bx bxl-youtube'></i>

    <p>Copyright Franck AÏGBA | @dive in code</p>
  </div>

</section>